### PR TITLE
add const in scanw function

### PR DESCRIPTION
**Pull request by gabol997**
adding const functions scanw();

### CODE REVIEW

**Comment by CyberShadow** [comment]
It doesn't seem to be `const` in the original header. I think you need to submit a patch for this to the upstream project (ncurses).

**Comment by gabol997** [comment]
in fact it is missing the const in the functions scanw and devivado like mvscanw I analyzed modified the code and the execute and yes the problem is there for lack of const a how to avoid this inserting in the code extern (C) int scanw (const char * fmt, ...) and it gets annoying to have to always type this for every function of the scanw mvscanw wscanw wmvscanw ...

**Comment by gabriel4g** [comment]
in fact this is really a problem and it is easy to fix, take a look, but if you still say that it’s not all right, I’ll use the library with my little modification.

**Comment by CyberShadow** [comment]
Looks like `const` was added in a later ncurses version.

This is included in #45.

**Pull request closed without merging**
