### PR TITLE
Improve dub file and build examples with dub

### PR DESCRIPTION
**Pull request by jaydg**
These changes finish the dub file for this package - now all possible variants can be built by dub.

I've also switched the examples to dub. These use the different package configurations.
These changes were tested with Travis (https://travis-ci.org/jaydg/ncurses).

If someone with the required permissions could register the repository on Travis, the "static" badge on the repo's README should be replaced by real build results.

### CODE REVIEW

**Comment by WalterBright** [comment]
What do I do?

**Comment by CyberShadow** [comment]
@WalterBright On https://travis-ci.org/D-Programming-Deimos/ncurses click "Activate repository"

**Comment by WalterBright** [comment]
There is no "Activate repository" button. There is an "Authorize application", but D-programming-diemos already has a green checkmark by it, indicating it already has access?

**Comment by CyberShadow** [comment]
@wilzbach Any ideas?

**Comment by wilzbach** [comment]
I am currently on my phone, but on this page https://travis-ci.org/D-Programming-Deimos/ncurses/settings it should roughly look like this:

![screenshot_20160930-041547] (https://cloud.githubusercontent.com/assets/4370550/18978605/c1bbdc04-86c4-11e6-9a83-5e3d30a33cc5.png)

If everything is activated it needs a new push event to trigger the build. 

Btw I usually use the Ruby gem Travis to enable projects - it's as simple as `travis enable` on the CLI ;-)

**Comment by CyberShadow** [comment]
"Build pushes" and "Build pull requests" are enabled, but the other tabs still say that the project is inactive. If I attempt to activate it, I get a nondescript error.

**Comment by WalterBright** [comment]
> https://travis-ci.org/D-Programming-Deimos/ncurses/settings

I get:
```
Hey, we're so glad 
you're here!
In order to view your repositories, 
please sign in.

Sign in with GitHub
```
I click on "Sign in with Github" and then I get:
```
Authorize application
Travis CI by @travis-ci would like permission to access your account
```
which looks nothing like that screenshot.

**Comment by schveiguy** [comment]
@WalterBright you have to first link your github account to Travis-CI, and then it lets you do admin stuff.

**Comment by WalterBright** [comment]
I added both of you.

**Comment by CyberShadow** [comment]
OK, looks like I enabled Travis for this repository.

> If someone with the required permissions could register the repository on Travis, the "static" badge on the repo's README should be replaced by real build results.

@jaydg Do you want to update the badge URL in your PR? (https://travis-ci.org/D-Programming-Deimos/ncurses.svg?branch=master)

**Comment by jaydg** [comment]
@CyberShadow done!

Thanks everybody for the effort!

**Pull request merged**
